const dishes = [
    { keyword: 'gaspacho', 
        name: 'Гаспачо',
        price: 195,
        category: 'soup', 
        count: '350 г', 
        image: 'images/soup1.jpg'},
    {keyword: 'mushroomsoup', 
        name: 'Грибной суп', 
        price: 180, 
        category: 'soup', 
        count: '350 г', 
        image: 'images/soup2.jpg'},
    {keyword: 'norwaysoop', 
        name: 'Норвежский суп', 
        price: 230, category: 'soup', 
        count: '350 г', 
        image: 'images/soup3.jpg'},
    {keyword: 'potato', 
        name: 'Жареная картошка с грибами', 
        price: 185, category: 'maindish', 
        count: '250 г', 
        image: 'images/maindish1.jpg'},
    {keyword: 'lasagna', 
        name: 'Лазанья', 
        price: 350, 
        category: 'maindish', 
        count: '310 г', 
        image: 'images/maindish2.jpg'},
    {keyword: 'cutlets', 
        name: 'Котлеты из курицы с картофельным пюре', 
        price: 210, 
        category: 'maindish', 
        count: '280 г', 
        image: 'images/maindish3.jpg'},
    {keyword: 'orangeJ', 
        name: 'Апельсиновый сок', 
        price: 90, category: 'drink', 
        count: '300 мл', 
        image: 'images/drink1.jpg'},
    {keyword: 'appleJ', 
        name: 'Яблочный сок', 
        price: 80, 
        category: 'drink', 
        count: '300 мл', 
        image: 'images/drink2.jpg'},
    {keyword: 'carrotJ', 
        name: 'Морковный сок', 
        price: 110, 
        category: 'drink', 
        count: '300 мл', 
        image: 'images/drink3.jpg'}
];